from(bucket: "test")
    |>range(start: :5, stop: :6)
    |>filter(fn: (r)=>r["Player Name"] == ":0")
    |>filter(fn: (r)=>r["_measurement"] == ":1")//teamName
    |>filter(fn: (r)=>r["Session"] == ":2")
    |>filter(fn: (r)=>r["_field"] == ":3")
    |>window(every: :7s)
    |>mean()
    |>duplicate(column: "_stop", as: "_time")
    |>window(every: inf)
