from(bucket: "test")
    |>range(start:-3y)
    |>filter(fn: (r)=>r["Player Name"] == ":0")
    |>group(columns: ["Session"], mode: "by")
    |>filter(fn: (r)=>r["Player Name"] == ":0")
    |>group(columns: ["Session","_measurement"], mode: "by")
    |>elapsed(columnName: "elapsed",timeColumn:"_time")
    |>sum(column:"elapsed")
    |>limit(n: 1)