from(bucket: "test")
    |>range(start:-3y)
    |>filter(fn: (r)=>r["Player Name"] == "Warren")
    |>filter(fn: (r)=>r["_field"] == "Sprint Distance")
    |>filter(fn: (r)=>r["_measurement"] == "TeamBit")
    |> window(every:30s)
    |> mean()
    |> duplicate(column: "_stop", as: "_time")
    |> window(every: inf)

// from(bucket: "test")
//     |>range(start:-3y)
//     |>filter(fn: (r)=>(r["Player Name"] == "Warren" and r["_field"] == "Velocity"))
//     |>group(columns: ["Session"], mode:"by")
//     |>limit(n: 500)
